name: Test cipherLi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Create venv
        run: python -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install cryptography

      - name: Run encryption/decryption test
        run: |
          source venv/bin/activate
          
          # Créer un fichier de test
          echo "Ceci est un test unique" > test_input.txt
          
          # Chiffrer le fichier
          python main.py encrypt "mon_mot_de_passe" test_input.txt encrypted.bin
          
          # Vérifier que le fichier chiffré existe
          ls encrypted.bin
          
          # Déchiffrer le fichier
          python main.py decrypt "mon_mot_de_passe" encrypted.bin decrypted.txt
          
          # Vérifier que le contenu déchiffré correspond
          if grep -q "Ceci est un test unique" decrypted.txt; then
            echo "Test réussi : contenu correct."
          else
            echo "Test échoué : contenu incorrect."
            exit 1
          fi
